# Generated by Django 3.1 on 2020-08-13 10:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('language', models.CharField(max_length=5, null=True)),
                ('copyright', models.CharField(max_length=50, null=True)),
                ('ttl', models.PositiveIntegerField(null=True)),
                ('atomLogo', models.URLField(null=True)),
                ('lastbuilddate', models.DateTimeField(null=True)),
                ('pubdate', models.DateTimeField(null=True)),
                ('nickname', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('following', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
                'ordering': ('-pubdate',),
                'unique_together': {('link', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0)),
                ('expires', models.DateTimeField(blank=True, help_text='When the entry should expire', null=True)),
                ('title', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('date', models.DateTimeField(help_text='When this entry says it was published')),
                ('author', models.TextField(blank=True)),
                ('url', models.TextField(blank=True, help_text='URL for the HTML for this entry', validators=[django.core.validators.URLValidator()])),
                ('comments_url', models.TextField(blank=True, help_text='URL for HTML comment submission page', validators=[django.core.validators.URLValidator()])),
                ('guid', models.TextField(blank=True, help_text='GUID for the entry, according to the feed')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='rss_feeder_api.feed')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ('-date',),
            },
        ),
    ]
