# Generated by Django 3.1 on 2020-08-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeder_api', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_owner',
            new_name='owner',
        ),
    ]
