# Generated by Django 3.1 on 2020-08-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeder_api', '0006_auto_20200818_1645'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('feed', 'guid')},
        ),
    ]
